### ISSUE TITLE
windows 安装出错

### ISSUE THREAD

**Issue by necan** [sisyphsu/hexo-enhancer#1]
windows 安装出错，试了几次，装不上。

**Comment by sisyphsu** [comment]
@necan 可以贴出来错误信息吗？

npm安装失败有可能是网络问题，可以试试yarn、cnpm等

**Comment by sisyphsu** [comment]
@necan 

windows安装失败的原因是此插件依赖另外一个插件`node-crc`，此插件内部依赖了python等，最终导致整体环境依赖比较复杂，尤其是对`Python`以及`C++`编译环境的依赖等。

我已经在新版本`1.0.4`中剔除掉了这个插件，并且在win7系统中实测没有问题，欢迎尝试~~

**Comment by leeningzzu** [comment]
![微信图片_20190406125259](https://user-images.githubusercontent.com/28948018/55665037-05966c80-586b-11e9-8076-2cce9f914767.png)
报错如上

**Comment by sisyphsu** [comment]
`Unexpected end of JSON input while parsing...`这样的错误，好像是npm内部缓存有问题。
可以参考：https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack

建议清理npm缓存，删除node_modules目录，然后重新install
```
npm cache clean --force
rm -Rf node_modules
npm install
```

**Comment by leeningzzu** [comment]
@sisyphsu 
![image](https://user-images.githubusercontent.com/28948018/55667550-3937bd80-5890-11e9-9f30-9d2c44059a2c.png)  装上了貌似加载不了 不好意思啊

**Comment by necan** [comment]
我自己写 Python 脚本代替了。

**Comment by sisyphsu** [comment]
@leeningzzu 这个错误是因为这个插件之前没有兼容到`keywords`为空的场景。

我在1.0.5版本中增加了`keywords`和`tags`为空的判断，使用1.0.5版本就不会出这个错误了。
