### ISSUE TITLE
怎么设置只启用部分功能呢？

### ISSUE THREAD

**Issue by zq1997** [sisyphsu/hexo-enhancer#2]
譬如，我想自动生成分类和标题，但是想在文件里自己手动指定`date`，而且也不希望使用abbr_link？
可以考虑在`_config.xml`里支持如此配置吗？

**Comment by sisyphsu** [comment]
这些功能都是可选的。

如果你的文件名里面没有日期前缀，它就不会自动生成`date`，如果你的文件中已经有了`date`，它也不会覆盖的，也就是说自动生成`data`有两个条件：

1. 文件中包括日期前缀
2. 文档内部没有`date`

`abbrlink`是这个插件额外新增的属性，不想用它的话，你直接忽略它就行。

**Comment by zq1997** [comment]
感谢，不过使用abbrlink似乎会导致post_path post_link post_asset等路径失效，有更好的处理方式吗

**Comment by sisyphsu** [comment]
使用`abbrlink`的话，post路径整体都会发生变化，可能得手动维护这些路径，我现在还想不到更好的办法，抱歉额。
