### ISSUE TITLE
希望可以将abbrlink中结尾的.html去掉

### ISSUE THREAD

**Issue by suyinLoong** [sisyphsu/hexo-enhancer#5]
使用abbrlink生成的短链接结尾都有个.html，能不能将其去掉？
`permalink: :year/:abbrlink`
使用这种配置，无法正常使用，点击会跳转到下载页面。
所以只能使用这种配置`permalink: :year/:abbrlink.html`
然而这种配置就会在链接结尾处生成.html后缀，能否将其去除？

**Comment by sisyphsu** [comment]
这个是`hexo`的功能，你可以按照官方文档修改`url`的格式，具体文档可以参考：
https://hexo.io/zh-cn/docs/permalinks#%E7%A4%BA%E4%BE%8B

注意链接`.../:title/`与`.../:title`是不一样的，`URL`末尾的斜杠是有意义的
